[package]
name = "xvcf"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = {features = ["libdeflate"], version = "0.49.0" }

syn = "2.0.87"


